name: setup-bluemoon
description: Install bluemoon for build packages

runs:
  using: composite
  steps:
    - name: Install dependencies
      shell: bash
      run: |
          sudo apt-get purge -y docker docker-engine docker.io containerd runc
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io squashfs-tools golang

    - name: Install bluemoon
      shell: bash
      run: |
          git clone https://github.com/nexryai/bluemoon bluemoon-src
          cd bluemoon-src && go build -o bluemoon
          sudo mv ./bluemoon /usr/bin/
          cd ..
          rm -rf bluemoon-src